import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Filter, Info, Search, ShieldAlert, XCircle } from "lucide-react";
import { useListActivity } from "@workspace/api-client-react";
import { AppLayout, PageIntro, Panel, QuietButton, SectionHeader, StatusBadge, Toast } from "@/components/layout/AppLayout";
import { useLanguage } from "@/lib/i18n";

export default function Logs() {
  const { t } = useLanguage();
  const activity = useListActivity({ limit: 100 });
  const [tab, setTab] = useState<"All activity" | "Success" | "Failures" | "Reviews">("All activity");
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState<string | null>(null);
  const logs = activity.data ?? [];
  const filtered = useMemo(() => logs.filter((log) => (tab === "All activity" || (tab === "Success" ? log.level === "success" : tab === "Failures" ? log.level === "error" : ["warning", "info"].includes(log.level))) && `${log.event} ${log.message}`.toLowerCase().includes(query.toLowerCase())), [logs, tab, query]);
  const icon = (level: string) => level === "success" ? <CheckCircle2 className="h-3.5 w-3.5" /> : level === "error" ? <XCircle className="h-3.5 w-3.5" /> : <Info className="h-3.5 w-3.5" />;
  const tabs: Array<"All activity" | "Success" | "Failures" | "Reviews"> = ["All activity", "Success", "Failures", "Reviews"];
  return <AppLayout activePage="logs" title={t("Activity log")} subtitle={t("An audit-friendly record of every workspace action")} headerAction={<QuietButton onClick={() => void activity.refetch()}>{t("Refresh")}</QuietButton>}>
    <PageIntro kicker={t("Traceability")} heading={t("Activity log")} detail={t("Real server events are retained here without session strings, passwords, verification codes, or API secrets.")} />
    <div className="mb-6 grid gap-3 sm:grid-cols-3"><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#174c3d] text-[#83dbae]"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#dcf1e8]">{logs.filter((log) => log.level === "success").length}</p><p className="font-mono text-[9px] uppercase text-[#69859e]">{t("Successful actions")}</p></div></Panel><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#40232f] text-[#f095a3]"><XCircle className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#f0d9df]">{logs.filter((log) => log.level === "error").length}</p><p className="font-mono text-[9px] uppercase text-[#69859e]">{t("Failures")}</p></div></Panel><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#453521] text-[#eabd7e]"><ShieldAlert className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#f0e0c8]">{logs.filter((log) => log.level === "warning").length}</p><p className="font-mono text-[9px] uppercase text-[#69859e]">{t("Warnings")}</p></div></Panel></div>
    <Panel className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#24384d] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><SectionHeader eyebrow={t("Audit trail")} title={t("Recent activity")} detail={t("Latest first · workspace timezone")} /><div className="relative w-full sm:w-[245px]"><Search className="absolute left-3.5 top-3 h-4 w-4 text-[#64819b]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("Search activity")} aria-label={t("Search activity")} className="w-full rounded-xl border border-[#2b445b] bg-[#0d1b2a] py-2.5 pl-10 pr-3 text-[11px] text-[#e5f0f8] outline-none" /></div></div><div className="flex items-center gap-1 overflow-x-auto border-b border-[#21364a] px-5 pt-3 sm:px-6">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 pb-3 pt-1 font-mono text-[10px] font-semibold uppercase ${tab === item ? "border-[#5eb3f1] text-[#a7d9f6]" : "border-transparent text-[#68839d]"}`}>{t(item)}</button>)}<Filter className="ml-auto mb-3 h-4 w-4 text-[#718ca3]" /></div>
      <div className="divide-y divide-[#21364a]">{filtered.map((log) => <div key={log.id} className="flex flex-col gap-3 px-5 py-4 sm:grid sm:grid-cols-[160px_minmax(220px,1fr)_120px] sm:items-center sm:px-6"><div className="flex items-center gap-2 font-mono text-[10px] text-[#708ba4]"><Clock3 className="h-3.5 w-3.5" />{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "medium" }).format(new Date(log.createdAt))}</div><div className="flex items-center gap-2.5"><span className={`grid h-7 w-7 place-items-center rounded-lg ${log.level === "success" ? "bg-[#174a3d] text-[#83dbae]" : log.level === "error" ? "bg-[#422431] text-[#ee9ba8]" : "bg-[#453521] text-[#eabe80]"}`}>{icon(log.level)}</span><div><p className="text-[12px] font-semibold text-[#d6e7f1]">{log.event}</p><p className="mt-1 text-[10px] text-[#718ca4]">{log.message}</p></div></div><StatusBadge status={log.level === "success" ? "active" : log.level === "error" ? "restricted" : "warning"} label={t(log.level)} /></div>)}</div>
      {!filtered.length && <div className="p-10 text-center text-[12px] text-[#7891a8]">{activity.isLoading ? t("Loading activity…") : t("No activity matches this view.")}</div>}
    </Panel>
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
  </AppLayout>;
}
