import { useState } from "react";
import { ChevronLeft, ChevronRight, Clock3, Filter, Plus, Send, SlidersHorizontal } from "lucide-react";
import { AppLayout, Modal, PageIntro, Panel, PrimaryButton, QuietButton, SectionHeader, StatusBadge, Toast } from "./_shared/AppLayout";

const days = [
  { date: 12, name: "Sun", events: [] },
  { date: 13, name: "Mon", events: [{ time: "08:45", title: "Office hours reminder", channel: "Remote Work Asia", color: "blue" }] },
  { date: 14, name: "Tue", events: [{ time: "09:30", title: "Community update", channel: "Hanoi Product Builders", color: "blue" }, { time: "13:00", title: "Weekly prompt", channel: "Indie Makers Vietnam", color: "warm" }] },
  { date: 15, name: "Wed", events: [{ time: "09:30", title: "Community update", channel: "Indie Makers Vietnam", color: "blue" }] },
  { date: 16, name: "Thu", events: [{ time: "11:00", title: "Founders round-up", channel: "Saigon Founders Table", color: "green" }] },
  { date: 17, name: "Fri", events: [] },
  { date: 18, name: "Sat", events: [{ time: "10:00", title: "Weekend reading list", channel: "Remote Work Asia", color: "warm" }] },
];

export function Calendar() {
  const [weekOffset, setWeekOffset] = useState(0);
  const [selectedEvent, setSelectedEvent] = useState<(typeof days)[number]["events"][number] & { date: number } | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const weekLabel = weekOffset === 0 ? "13 – 19 January 2025" : weekOffset > 0 ? "20 – 26 January 2025" : "06 – 12 January 2025";
  return <AppLayout activePage="calendar" title="Calendar" subtitle="A shared view of scheduled, reviewed content" headerAction={<QuietButton onClick={() => setToast("Calendar synced with workspace timezone ICT")}><SlidersHorizontal className="h-3.5 w-3.5" />Calendar settings</QuietButton>}>
    <PageIntro kicker="Publishing calendar" heading="Schedule at a glance" detail="A quiet week is a good week. Every card below has a verified destination and an accountable owner." action={<PrimaryButton onClick={() => window.location.assign("/__mockup/telecampaign/Campaigns")}><Plus className="h-4 w-4" />Schedule a post</PrimaryButton>} />
    <Panel className="overflow-hidden">
      <div className="flex flex-col gap-4 border-b border-[#24384d] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-2"><button onClick={() => setWeekOffset((value) => value - 1)} className="rounded-lg border border-[#2b445b] p-2 text-[#7c97ad] hover:bg-[#192e41] hover:text-[#dcecf6]" aria-label="Previous week"><ChevronLeft className="h-4 w-4" /></button><button onClick={() => setWeekOffset(0)} className="rounded-lg border border-[#2b445b] px-3 py-2 font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-[#9cb5c8] hover:bg-[#192e41]">Today</button><button onClick={() => setWeekOffset((value) => value + 1)} className="rounded-lg border border-[#2b445b] p-2 text-[#7c97ad] hover:bg-[#192e41] hover:text-[#dcecf6]" aria-label="Next week"><ChevronRight className="h-4 w-4" /></button><span className="ml-2 text-[14px] font-semibold text-[#dceaf4]">{weekLabel}</span></div><div className="flex items-center gap-2"><button className="rounded-lg border border-[#4b7597] bg-[#193c5b] px-3 py-2 font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-[#a8daf8]">Week</button><button onClick={() => setToast("Month view is ready for the next release")} className="rounded-lg border border-transparent px-3 py-2 font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-[#66839c] hover:text-[#b5ccdc]">Month</button><button onClick={() => setToast("Filters opened")} className="ml-1 rounded-lg border border-[#2b445b] p-2 text-[#7892a9] hover:bg-[#192e41]" aria-label="Filter calendar"><Filter className="h-4 w-4" /></button></div></div>
      <div className="overflow-x-auto"><div className="min-w-[900px] grid grid-cols-7 divide-x divide-[#22394e]"><div className="col-span-7 grid grid-cols-7 border-b border-[#22394e] bg-[#0e1b29]">{days.map((day) => <div key={day.date} className={`px-3 py-3 text-center ${day.date === 14 ? "bg-[#12304a]" : ""}`}><p className="font-mono text-[9px] font-semibold uppercase tracking-[0.14em] text-[#68849d]">{day.name}</p><p className={`mt-1 text-[17px] font-semibold ${day.date === 14 ? "text-[#83cdf8]" : "text-[#c3d6e4]"}`}>{day.date}</p></div>)}</div>{days.map((day) => <div key={day.date} className={`min-h-[420px] border-b border-[#22394e] p-2.5 ${day.date === 14 ? "bg-[#102337]/70" : ""}`}>{day.events.length === 0 ? <div className="mt-3 border-t border-dashed border-[#274158] pt-3 text-center font-mono text-[9px] text-[#48657e]">Open</div> : <div className="space-y-2">{day.events.map((event) => <button key={event.title} onClick={() => setSelectedEvent({ ...event, date: day.date })} className={`w-full rounded-xl border p-3 text-left transition hover:-translate-y-0.5 ${event.color === "warm" ? "border-[#665033] bg-[#352a1b] hover:border-[#977246]" : event.color === "green" ? "border-[#2c594c] bg-[#14362f] hover:border-[#478875]" : "border-[#2b5778] bg-[#14334d] hover:border-[#4a87b3]"}`}><div className="mb-2 flex items-center justify-between"><span className={`font-mono text-[9px] font-semibold ${event.color === "warm" ? "text-[#e8b972]" : event.color === "green" ? "text-[#79d3a4]" : "text-[#82cafa]"}`}>{event.time}</span><Send className="h-3 w-3 text-[#718aa0]" /></div><p className="line-clamp-2 text-[11px] font-semibold leading-4 text-[#d7e7f1]">{event.title}</p><p className="mt-2 truncate font-mono text-[9px] text-[#7894aa]">{event.channel}</p></button>)}</div>}</div>)}</div></div>
      <div className="flex flex-wrap items-center gap-5 border-t border-[#22394e] px-5 py-4 font-mono text-[10px] text-[#6d879e] sm:px-6"><span className="inline-flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#5db3f1]" />Scheduled</span><span className="inline-flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#e4ad69]" />Needs review</span><span className="inline-flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#72d1a0]" />Published</span><span className="ml-auto">All times in ICT (UTC+7)</span></div>
    </Panel>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Today" title="Tuesday’s run sheet" detail="2 posts scheduled across 2 destinations" /><div className="space-y-3"><div className="flex items-center gap-3 rounded-xl border border-[#2c5371] bg-[#14334d] p-3"><Clock3 className="h-4 w-4 text-[#80c9f8]" /><span className="font-mono text-[11px] text-[#b9d6e8]">09:30</span><span className="h-4 w-px bg-[#416981]" /><span className="text-[11px] font-medium text-[#d4e6f0]">Community update</span><span className="ml-auto font-mono text-[9px] text-[#7796ae]">Hanoi Product Builders</span></div><div className="flex items-center gap-3 rounded-xl border border-[#654d31] bg-[#33291b] p-3"><Clock3 className="h-4 w-4 text-[#e4b16c]" /><span className="font-mono text-[11px] text-[#ead0a2]">13:00</span><span className="h-4 w-px bg-[#6f5939]" /><span className="text-[11px] font-medium text-[#dfd3bd]">Weekly prompt</span><span className="ml-auto font-mono text-[9px] text-[#a7906d]">Indie Makers Vietnam</span></div></div></Panel><Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Capacity" title="Publishing windows" detail="Healthy spacing between scheduled posts" /><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full border-[5px] border-[#347ea9] border-r-[#263e53] text-[15px] font-semibold text-[#bfe5fa]">18</div><div><p className="text-[12px] font-semibold text-[#d8e8f1]">scheduled posts</p><p className="mt-1 text-[11px] leading-5 text-[#7791a8]">No overlapping windows or permission conflicts this week.</p></div></div></Panel></div>
    {selectedEvent && <Modal title={selectedEvent.title} description={`Tuesday, ${selectedEvent.date} January · ${selectedEvent.time} ICT`} onClose={() => setSelectedEvent(null)}><div className="space-y-4"><div className="rounded-xl border border-[#2a465e] bg-[#0e1b2a] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#68839c]">Destination</p><p className="mt-2 text-[13px] font-semibold text-[#dcebf4]">{selectedEvent.channel}</p></div><div className="flex items-center gap-2"><StatusBadge status="scheduled" label="Approved & scheduled" /></div><div className="flex justify-end gap-2"><QuietButton onClick={() => { setSelectedEvent(null); setToast("Edit flow opened from calendar"); }}>Edit schedule</QuietButton><PrimaryButton onClick={() => { setSelectedEvent(null); setToast("Post preview opened"); }}>Preview post</PrimaryButton></div></div></Modal>}
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
  </AppLayout>;
}