import { useState } from "react";
import { ArrowLeft, ArrowRight, CalendarClock, Check, ChevronRight, CirclePause, FileText, Plus, Send, Trash2 } from "lucide-react";
import { AppLayout, Input, Modal, PageIntro, Panel, PrimaryButton, QuietButton, SectionHeader, StatusBadge, Toast } from "./_shared/AppLayout";

type Campaign = { id: number; name: string; destinations: string; schedule: string; author: string; posts: number; status: "scheduled" | "draft" | "paused" };
const initialCampaigns: Campaign[] = [
  { id: 1, name: "January community notes", destinations: "3 destinations", schedule: "Today · 09:30 ICT", author: "Minh Pham", posts: 12, status: "scheduled" },
  { id: 2, name: "Weekly conversation starter", destinations: "2 destinations", schedule: "Wed · 13:00 ICT", author: "Minh Pham", posts: 8, status: "scheduled" },
  { id: 3, name: "Remote work office hours", destinations: "1 destination", schedule: "Not scheduled", author: "Linh Tran", posts: 4, status: "draft" },
  { id: 4, name: "Product feedback round-up", destinations: "4 destinations", schedule: "Paused · review needed", author: "Minh Pham", posts: 16, status: "paused" },
];

export function Campaigns() {
  const [campaigns, setCampaigns] = useState(initialCampaigns);
  const [filter, setFilter] = useState("All campaigns");
  const [wizardStep, setWizardStep] = useState(0);
  const [showWizard, setShowWizard] = useState(false);
  const [name, setName] = useState("");
  const [showDelete, setShowDelete] = useState<Campaign | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const shown = campaigns.filter((campaign) => filter === "All campaigns" || campaign.status === filter.toLowerCase().replace(" ", ""));

  function createCampaign() {
    setCampaigns((current) => [{ id: Date.now(), name: name || "Untitled campaign", destinations: "1 destination", schedule: "Not scheduled", author: "Minh Pham", posts: 0, status: "draft" }, ...current]);
    setShowWizard(false); setWizardStep(0); setName(""); setToast("Campaign saved as draft");
  }
  function changeStatus(campaign: Campaign) {
    setCampaigns((current) => current.map((item) => item.id === campaign.id ? { ...item, status: item.status === "paused" ? "scheduled" : "paused", schedule: item.status === "paused" ? "Tomorrow · 09:00 ICT" : "Paused · review needed" } : item));
    setToast(campaign.status === "paused" ? "Campaign resumed" : "Campaign paused");
  }

  return <AppLayout activePage="campaigns" title="Campaigns" subtitle="Approved content, destinations, and schedules" headerAction={<QuietButton onClick={() => setShowWizard(true)}><Plus className="h-3.5 w-3.5" />New campaign</QuietButton>}>
    <PageIntro kicker="Publishing workflow" heading="Campaigns" detail="Build a clear publishing plan, check its scope, then schedule it. Drafts stay private until you choose a time." action={<PrimaryButton onClick={() => setShowWizard(true)}><Plus className="h-4 w-4" />Create campaign</PrimaryButton>} />
    <Panel className="overflow-hidden">
      <div className="flex flex-col gap-4 border-b border-[#24384d] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><SectionHeader eyebrow="Your workspace" title="All campaigns" detail={`${campaigns.length} plans across your approved destinations`} /><div className="flex rounded-xl border border-[#2a4359] bg-[#0d1b2a] p-1">{["All campaigns", "Scheduled", "Draft", "Paused"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold transition ${filter === item ? "bg-[#24547b] text-[#dff1fc]" : "text-[#7892a9] hover:text-[#c9dce9]"}`}>{item}</button>)}</div></div>
      <div className="hidden grid-cols-[minmax(240px,1.5fr)_150px_165px_120px_32px] gap-4 border-b border-[#21364a] bg-[#0e1b29] px-6 py-3 font-mono text-[9px] font-semibold uppercase tracking-[0.13em] text-[#617d96] md:grid"><span>Campaign</span><span>Scope</span><span>Schedule</span><span>Status</span><span /></div>
      <div className="divide-y divide-[#21364a]">{shown.map((campaign) => <div key={campaign.id} className="grid gap-3 px-5 py-4 md:grid-cols-[minmax(240px,1.5fr)_150px_165px_120px_32px] md:items-center md:gap-4 md:px-6"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${campaign.status === "scheduled" ? "bg-[#17486d] text-[#8bcdf7]" : campaign.status === "paused" ? "bg-[#503c27] text-[#e9c38c]" : "bg-[#303447] text-[#bac2d1]"}`}><FileText className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-[12px] font-semibold text-[#dceaf4]">{campaign.name}</p><p className="mt-1 truncate font-mono text-[10px] text-[#6f8aa3]">{campaign.posts} posts · Created by {campaign.author}</p></div></div><span className="text-[11px] text-[#9bb1c3]">{campaign.destinations}</span><span className="text-[11px] text-[#9bb1c3]">{campaign.schedule}</span><StatusBadge status={campaign.status} label={campaign.status} /><div className="flex items-center gap-1"><button onClick={() => changeStatus(campaign)} className="rounded-lg p-2 text-[#718da6] hover:bg-[#192e41] hover:text-[#e6f1f8]" aria-label={campaign.status === "paused" ? "Resume campaign" : "Pause campaign"}><CirclePause className="h-4 w-4" /></button><button onClick={() => setShowDelete(campaign)} className="rounded-lg p-2 text-[#718da6] hover:bg-[#351f2a] hover:text-[#f29ba8]" aria-label="Delete campaign"><Trash2 className="h-4 w-4" /></button></div></div>)}</div>
      {shown.length === 0 && <div className="p-10 text-center text-[12px] text-[#7891a8]">No campaigns in this state.</div>}
      <div className="border-t border-[#21364a] px-5 py-4 font-mono text-[10px] text-[#66829b]">Campaigns are limited to destinations where your account has explicit posting permission.</div>
    </Panel>
    {showWizard && <Modal title="Create a campaign" description="A short review before anything can be scheduled." onClose={() => { setShowWizard(false); setWizardStep(0); }} wide>
      <div className="mb-7 flex items-center justify-between">{["Plan", "Scope", "Schedule", "Review"].map((label, index) => <div key={label} className="flex items-center"><div className={`flex items-center gap-2 ${index <= wizardStep ? "text-[#a9dafa]" : "text-[#607990]"}`}><span className={`grid h-7 w-7 place-items-center rounded-full border font-mono text-[10px] ${index < wizardStep ? "border-[#3f9b77] bg-[#174f3f] text-[#9ce0bd]" : index === wizardStep ? "border-[#5eb4f1] bg-[#1b5279] text-[#e2f4ff]" : "border-[#304a60] bg-[#162839]"}`}>{index < wizardStep ? <Check className="h-3.5 w-3.5" /> : index + 1}</span><span className="hidden text-[11px] font-semibold sm:block">{label}</span></div>{index < 3 && <ChevronRight className="mx-2 h-4 w-4 text-[#3f5a70] sm:mx-4" />}</div>)}</div>
      {wizardStep === 0 && <div className="space-y-5"><Input label="Campaign name" value={name} onChange={setName} placeholder="e.g. February community check-in" /><label className="block"><span className="mb-2 block font-mono text-[9px] font-semibold uppercase tracking-[0.13em] text-[#7892a9]">Content format</span><div className="grid gap-2 sm:grid-cols-2"><button className="rounded-xl border border-[#4e8ab5] bg-[#173650] p-4 text-left"><p className="text-[12px] font-semibold text-[#dceefa]">Compose a post</p><p className="mt-1 text-[11px] text-[#87a9c1]">Write or paste an approved message</p></button><button className="rounded-xl border border-[#2b445b] bg-[#0e1b2a] p-4 text-left"><p className="text-[12px] font-semibold text-[#c9d9e6]">Import a content set</p><p className="mt-1 text-[11px] text-[#718ba3]">Use an existing reviewed draft</p></button></div></label></div>}
      {wizardStep === 1 && <div className="space-y-4"><p className="text-[12px] text-[#9db2c4]">Select only destinations where your connected account has posting permission.</p>{["Hanoi Product Builders", "Indie Makers Vietnam", "Remote Work Asia"].map((destination, index) => <label key={destination} className="flex cursor-pointer items-center gap-3 rounded-xl border border-[#2b445b] bg-[#0e1b2a] p-4 hover:border-[#47708f]"><input type="checkbox" defaultChecked={index < 2} className="h-4 w-4 accent-[#2992ee]" /><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#1b4b70] text-[#8dcefa]"><Send className="h-4 w-4" /></span><span className="flex-1"><span className="block text-[12px] font-semibold text-[#dceaf4]">{destination}</span><span className="mt-1 block font-mono text-[10px] text-[#718ca4]">{index === 0 ? "486" : index === 1 ? "1,204" : "3,842"} members · permission verified</span></span><StatusBadge status="active" label="Allowed" /></label>)}</div>}
      {wizardStep === 2 && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Input label="Publish date" value="15 Jan 2025" onChange={() => undefined} type="text" /><Input label="Publish time" value="09:30" onChange={() => undefined} type="text" /></div><div className="rounded-xl border border-[#665034] bg-[#302719] p-4 text-[12px] leading-5 text-[#e0c18e]"><CalendarClock className="mb-2 h-4 w-4 text-[#e8b56e]" />Posts will use the workspace timezone <strong className="text-[#f0d09c]">ICT (UTC+7)</strong>. You can pause or edit this campaign at any time before it runs.</div></div>}
      {wizardStep === 3 && <div className="space-y-3"><div className="rounded-xl border border-[#2c4b63] bg-[#0d1b2a] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#68839d]">Campaign</p><p className="mt-2 text-[15px] font-semibold text-[#e5f0f7]">{name || "Untitled campaign"}</p><p className="mt-1 text-[11px] text-[#7893a9]">2 approved destinations · 1 post per destination</p></div><div className="rounded-xl border border-[#2c4b63] bg-[#0d1b2a] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#68839d]">Schedule</p><p className="mt-2 text-[13px] text-[#d4e4ee]">15 January 2025 at 09:30 ICT</p></div><div className="flex items-start gap-2 pt-2 text-[11px] leading-5 text-[#8399ad]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#76d19d]" />This review confirms the destination scope. No message will be sent outside these selected channels.</div></div>}
      <div className="mt-7 flex justify-between border-t border-[#253c52] pt-5">{wizardStep > 0 ? <QuietButton onClick={() => setWizardStep((stepValue) => stepValue - 1)}><ArrowLeft className="h-3.5 w-3.5" />Back</QuietButton> : <span />}{wizardStep < 3 ? <PrimaryButton onClick={() => setWizardStep((stepValue) => stepValue + 1)}>Continue <ArrowRight className="h-3.5 w-3.5" /></PrimaryButton> : <PrimaryButton onClick={createCampaign}><Check className="h-3.5 w-3.5" />Save campaign</PrimaryButton>}</div>
    </Modal>}
    {showDelete && <Modal title="Delete this campaign?" description="This removes the campaign and its schedule from the workspace. This action cannot be undone." onClose={() => setShowDelete(null)}><div className="flex justify-end gap-2"><QuietButton onClick={() => setShowDelete(null)}>Keep campaign</QuietButton><button onClick={() => { setCampaigns((current) => current.filter((item) => item.id !== showDelete.id)); setShowDelete(null); setToast("Campaign deleted"); }} className="inline-flex items-center gap-2 rounded-xl bg-[#8f3f51] px-4 py-2.5 text-[12px] font-semibold text-[#ffedf0] hover:bg-[#a74a5d]"><Trash2 className="h-3.5 w-3.5" />Delete campaign</button></div></Modal>}
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
  </AppLayout>;
}