import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Download, Filter, Info, RefreshCw, Search, ShieldAlert, XCircle } from "lucide-react";
import { AppLayout, PageIntro, Panel, PrimaryButton, QuietButton, SectionHeader, StatusBadge, Toast } from "./_shared/AppLayout";

type Log = { id: number; time: string; action: string; campaign: string; destination: string; account: string; status: "success" | "failed" | "warning"; note: string };
const seedLogs: Log[] = [
  { id: 1, time: "14 Jan · 09:31:04", action: "Post delivered", campaign: "January community notes", destination: "Hanoi Product Builders", account: "Minh · primary", status: "success", note: "Message delivered to Telegram" },
  { id: 2, time: "14 Jan · 09:30:58", action: "Post delivered", campaign: "January community notes", destination: "Indie Makers Vietnam", account: "Minh · primary", status: "success", note: "Message delivered to Telegram" },
  { id: 3, time: "14 Jan · 08:46:12", action: "Permission check", campaign: "Remote work office hours", destination: "Remote Work Asia", account: "TeleCampaign Bot", status: "warning", note: "Destination permission re-verified" },
  { id: 4, time: "13 Jan · 16:12:28", action: "Post failed", campaign: "Product feedback round-up", destination: "Design Systems Club", account: "Community backup", status: "failed", note: "Admin permission could not be confirmed" },
  { id: 5, time: "13 Jan · 13:00:06", action: "Post delivered", campaign: "Weekly conversation starter", destination: "Indie Makers Vietnam", account: "Minh · primary", status: "success", note: "Message delivered to Telegram" },
  { id: 6, time: "13 Jan · 09:12:46", action: "Campaign paused", campaign: "Product feedback round-up", destination: "4 destinations", account: "Minh · primary", status: "warning", note: "Paused by Minh Pham" },
];

export function Logs() {
  const [logs, setLogs] = useState(seedLogs);
  const [tab, setTab] = useState("All activity");
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState<string | null>(null);
  const filtered = useMemo(() => logs.filter((log) => (tab === "All activity" || (tab === "Success" ? log.status === "success" : tab === "Failures" ? log.status === "failed" : log.status === "warning")) && `${log.action} ${log.campaign} ${log.destination}`.toLowerCase().includes(query.toLowerCase())), [logs, tab, query]);
  return <AppLayout activePage="logs" title="Activity log" subtitle="An audit-friendly record of every workspace action" headerAction={<QuietButton onClick={() => setToast("Activity export prepared") }><Download className="h-3.5 w-3.5" />Export log</QuietButton>}>
    <PageIntro kicker="Traceability" heading="Activity log" detail="See what happened, where it happened, and which managed identity performed the action. Logs are retained for 90 days." action={<PrimaryButton onClick={() => setToast("Activity export prepared as CSV")}><Download className="h-4 w-4" />Export CSV</PrimaryButton>} />
    <div className="mb-6 grid gap-3 sm:grid-cols-3"><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#174c3d] text-[#83dbae]"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#dcf1e8]">1,284</p><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#69859e]">Successful actions</p></div></Panel><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#40232f] text-[#f095a3]"><XCircle className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#f0d9df]">12</p><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#69859e]">Failures this month</p></div></Panel><Panel className="flex items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#453521] text-[#eabd7e]"><ShieldAlert className="h-4 w-4" /></span><div><p className="text-[21px] font-semibold text-[#f0e0c8]">4</p><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#69859e]">Permission reviews</p></div></Panel></div>
    <Panel className="overflow-hidden">
      <div className="flex flex-col gap-4 border-b border-[#24384d] p-5 sm:p-6 lg:flex-row lg:items-center lg:justify-between"><SectionHeader eyebrow="Audit trail" title="Recent activity" detail="Latest first · workspace timezone ICT" /><div className="relative w-full lg:w-[245px]"><Search className="absolute left-3.5 top-3 h-4 w-4 text-[#64819b]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activity" className="w-full rounded-xl border border-[#2b445b] bg-[#0d1b2a] py-2.5 pl-10 pr-3 text-[11px] text-[#e5f0f8] outline-none placeholder:text-[#526d87] focus:border-[#58aef1]" /></div></div>
      <div className="flex items-center gap-1 overflow-x-auto border-b border-[#21364a] px-5 pt-3 sm:px-6">{["All activity", "Success", "Failures", "Reviews"].map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 pb-3 pt-1 font-mono text-[10px] font-semibold uppercase tracking-[0.08em] transition ${tab === item ? "border-[#5eb3f1] text-[#a7d9f6]" : "border-transparent text-[#68839d] hover:text-[#b9cede]"}`}>{item}</button>)}<button onClick={() => setToast("Filters opened")} className="ml-auto mb-2 rounded-lg p-2 text-[#718ca3] hover:bg-[#192e41] hover:text-[#dcecf5]" aria-label="Filter activity"><Filter className="h-4 w-4" /></button></div>
      <div className="divide-y divide-[#21364a]">{filtered.map((log) => <div key={log.id} className="flex flex-col gap-3 px-5 py-4 sm:grid sm:grid-cols-[145px_minmax(175px,1fr)_minmax(150px,1fr)_120px_112px] sm:items-center sm:gap-4 sm:px-6"><div className="flex items-center gap-2 font-mono text-[10px] text-[#708ba4]"><Clock3 className="h-3.5 w-3.5 text-[#55738d]" />{log.time}</div><div className="flex items-center gap-2.5"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-lg ${log.status === "success" ? "bg-[#174a3d] text-[#83dbae]" : log.status === "failed" ? "bg-[#422431] text-[#ee9ba8]" : "bg-[#453521] text-[#eabe80]"}`}>{log.status === "success" ? <CheckCircle2 className="h-3.5 w-3.5" /> : log.status === "failed" ? <XCircle className="h-3.5 w-3.5" /> : <Info className="h-3.5 w-3.5" />}</span><div><p className="text-[12px] font-semibold text-[#d6e7f1]">{log.action}</p><p className="mt-1 text-[10px] text-[#718ca4]">{log.note}</p></div></div><div className="pl-9 sm:pl-0"><p className="truncate text-[11px] text-[#abc0d0]">{log.campaign}</p><p className="mt-1 truncate font-mono text-[10px] text-[#668199]">{log.destination}</p></div><span className="hidden truncate text-[10px] text-[#8099ad] sm:block">{log.account}</span><div className="flex items-center justify-between pl-9 sm:justify-end sm:pl-0"><StatusBadge status={log.status} label={log.status === "success" ? "Success" : log.status === "failed" ? "Failed" : "Review"} />{log.status === "failed" && <button onClick={() => { setLogs((current) => current.map((item) => item.id === log.id ? { ...item, status: "warning", note: "Retry queued for permission review" } : item)); setToast("Retry queued after permission review"); }} className="ml-2 inline-flex items-center gap-1 font-mono text-[9px] font-semibold uppercase tracking-[0.07em] text-[#79c5f7] hover:text-[#b7e4fc]"><RefreshCw className="h-3 w-3" />Retry</button>}</div></div>)}</div>
      {filtered.length === 0 && <div className="p-10 text-center text-[12px] text-[#7891a8]">No activity matches this view.</div>}
      <div className="flex items-center justify-between border-t border-[#21364a] px-5 py-4 font-mono text-[10px] text-[#66829b] sm:px-6"><span>Showing {filtered.length} of {logs.length} events</span><span className="hidden sm:block">Retention: 90 days</span></div>
    </Panel>
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
  </AppLayout>;
}