import { useState } from "react";
import { BellRing, Check, ChevronRight, KeyRound, LockKeyhole, LogOut, Mail, Save, ShieldCheck, Smartphone, Terminal } from "lucide-react";
import { AppLayout, Input, Modal, PageIntro, Panel, PrimaryButton, QuietButton, SectionHeader, StatusBadge, Toast } from "./_shared/AppLayout";

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) {
  return <button onClick={onChange} className="flex items-center gap-3 text-left" aria-label={`Toggle ${label}`}><span className={`relative h-5 w-9 rounded-full border transition ${checked ? "border-[#2c8b68] bg-[#1b6a50]" : "border-[#41536a] bg-[#243446]"}`}><span className={`absolute top-[3px] h-3 w-3 rounded-full bg-[#e8f3fa] transition ${checked ? "left-[18px]" : "left-[3px]"}`} /></span><span className="sr-only">{label}</span></button>;
}

export function Settings() {
  const [tab, setTab] = useState("Security");
  const [twoFactor, setTwoFactor] = useState(true);
  const [alerts, setAlerts] = useState(true);
  const [weekly, setWeekly] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [confirm, setConfirm] = useState(false);
  const [integration, setIntegration] = useState(false);
  return <AppLayout activePage="settings" title="Settings" subtitle="Workspace preferences and secure integration controls">
    <PageIntro kicker="Workspace control" heading="Settings" detail="Keep the workspace aligned with your team’s operating rhythm. Changes save locally in this preview." action={<PrimaryButton onClick={() => setToast("Settings saved")}><Save className="h-4 w-4" />Save changes</PrimaryButton>} />
    <div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]">
      <Panel className="h-fit p-2"><div className="p-3 font-mono text-[9px] font-semibold uppercase tracking-[0.16em] text-[#627e98]">Workspace settings</div>{[["Security", LockKeyhole], ["Notifications", BellRing], ["Telegram integration", Terminal]].map(([label, Icon]) => <button key={label as string} onClick={() => setTab(label as string)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[12px] font-medium transition ${tab === label ? "bg-[#193a5a] text-[#e1f1fb]" : "text-[#8299ae] hover:bg-[#16293a] hover:text-[#d6e6f0]"}`}><Icon className={`h-4 w-4 ${tab === label ? "text-[#71c2fa]" : "text-[#617e98]"}`} />{label as string}<ChevronRight className={`ml-auto h-3.5 w-3.5 ${tab === label ? "text-[#70bdf1]" : "text-[#526d86]"}`} /></button>)}</Panel>
      <div className="space-y-5">
        {tab === "Security" && <><Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Access policy" title="Security" detail="Your workspace is protected by least-privilege access and an auditable activity log." /><div className="space-y-1 divide-y divide-[#21364a]"><div className="flex items-center gap-4 py-4 first:pt-0"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#174b3f] text-[#83dbae]"><ShieldCheck className="h-4 w-4" /></span><div className="flex-1"><p className="text-[12px] font-semibold text-[#dcebf3]">Two-factor authentication</p><p className="mt-1 text-[11px] text-[#728ca3]">Required for all workspace owners and publishers.</p></div><Toggle checked={twoFactor} onChange={() => setTwoFactor((value) => !value)} label="two-factor authentication" /></div><div className="flex items-center gap-4 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#194267] text-[#8dcef6]"><KeyRound className="h-4 w-4" /></span><div className="flex-1"><p className="text-[12px] font-semibold text-[#dcebf3]">Session timeout</p><p className="mt-1 text-[11px] text-[#728ca3]">Sign out after 30 minutes of inactivity.</p></div><button onClick={() => setToast("Session timeout options opened")} className="font-mono text-[10px] font-semibold uppercase tracking-[0.08em] text-[#75bff1]">30 min</button></div><div className="flex items-center gap-4 py-4 last:pb-0"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#3f3526] text-[#e7b772]"><Smartphone className="h-4 w-4" /></span><div className="flex-1"><p className="text-[12px] font-semibold text-[#dcebf3]">Active sessions</p><p className="mt-1 text-[11px] text-[#728ca3]">2 trusted devices · Last sign-in today, 08:42 ICT</p></div><button onClick={() => setConfirm(true)} className="font-mono text-[10px] font-semibold uppercase tracking-[0.08em] text-[#e99aa7] hover:text-[#ffbdc6]">Revoke all</button></div></div></Panel><Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Profile" title="Account details" detail="The workspace owner shown in audit events." /><div className="grid gap-4 sm:grid-cols-2"><Input label="Full name" value="Minh Pham" onChange={() => undefined} /><Input label="Work email" value="minh@northstar.community" onChange={() => undefined} type="email" /></div></Panel></>}
        {tab === "Notifications" && <Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Keep informed" title="Notifications" detail="Choose which operational signals deserve your attention." /><div className="space-y-1 divide-y divide-[#21364a]"><div className="flex items-center gap-4 py-4 first:pt-0"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#194267] text-[#8dcef6]"><BellRing className="h-4 w-4" /></span><div className="flex-1"><p className="text-[12px] font-semibold text-[#dcebf3]">Delivery and permission alerts</p><p className="mt-1 text-[11px] text-[#728ca3]">Get notified when a post fails or a destination needs review.</p></div><Toggle checked={alerts} onChange={() => setAlerts((value) => !value)} label="delivery and permission alerts" /></div><div className="flex items-center gap-4 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#3f3526] text-[#e7b772]"><Mail className="h-4 w-4" /></span><div className="flex-1"><p className="text-[12px] font-semibold text-[#dcebf3]">Weekly workspace summary</p><p className="mt-1 text-[11px] text-[#728ca3]">A Monday digest of delivery, reach, and pending reviews.</p></div><Toggle checked={weekly} onChange={() => setWeekly((value) => !value)} label="weekly workspace summary" /></div></div><div className="mt-6 rounded-xl border border-[#2a465e] bg-[#0e1b2a] p-4"><p className="text-[12px] font-semibold text-[#d7e7f1]">Notification destination</p><p className="mt-1 text-[11px] text-[#718ba4]">minh@northstar.community</p><button onClick={() => setToast("Email destination editing opened")} className="mt-3 font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-[#74c1f2]">Change email</button></div></Panel>}
        {tab === "Telegram integration" && <><Panel className="border-[#665035] bg-[#182436] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#614727] text-[#efc181]"><Terminal className="h-5 w-5" /></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-[16px] font-semibold text-[#f0e7d8]">Telegram integration is not configured</h2><StatusBadge status="warning" label="Action needed" /></div><p className="mt-2 max-w-xl text-[12px] leading-5 text-[#c0a881]">Configure <strong className="font-mono text-[#e6c48f]">TELEGRAM_API_ID</strong> and <strong className="font-mono text-[#e6c48f]">TELEGRAM_API_HASH</strong> to connect an account.</p><p className="mt-3 text-[11px] leading-5 text-[#9d896b]">These values belong in your server environment. Never paste them, a session string, password, or verification code into the browser.</p></div><PrimaryButton onClick={() => setIntegration(true)}>Configure integration</PrimaryButton></div></Panel><Panel className="p-5 sm:p-6"><SectionHeader eyebrow="Integration guide" title="Before you connect" detail="A safe checklist for your Telegram administrator." /><div className="space-y-3">{["Add API credentials to the server environment, not the client.", "Connect only identities you are authorized to operate.", "Review posting permission for every destination before scheduling."].map((item, index) => <div key={item} className="flex items-start gap-3 rounded-xl border border-[#2a4359] bg-[#0e1b2a] p-3.5"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#1c5079] font-mono text-[9px] text-[#a7dcfa]">{index + 1}</span><p className="text-[11px] leading-5 text-[#9bb2c3]">{item}</p><Check className="ml-auto mt-0.5 h-3.5 w-3.5 shrink-0 text-[#6fcb9b]" /></div>)}</div></Panel></>}
      </div>
    </div>
    {confirm && <Modal title="Revoke all active sessions?" description="This signs out every trusted device except the one you are using now. You can sign in again after confirmation." onClose={() => setConfirm(false)}><div className="flex justify-end gap-2"><QuietButton onClick={() => setConfirm(false)}>Cancel</QuietButton><button onClick={() => { setConfirm(false); setToast("All other sessions revoked"); }} className="inline-flex items-center gap-2 rounded-xl bg-[#8f3f51] px-4 py-2.5 text-[12px] font-semibold text-[#ffedf0] hover:bg-[#a74a5d]"><LogOut className="h-3.5 w-3.5" />Revoke sessions</button></div></Modal>}
    {integration && <Modal title="Configure Telegram integration" description="Environment configuration is managed on your server. This screen intentionally never accepts or displays secret values." onClose={() => setIntegration(false)}><div className="space-y-4"><div className="rounded-xl border border-[#2c465d] bg-[#0d1b2a] p-4 font-mono text-[11px] leading-6 text-[#9bb5c8]"><div><span className="text-[#6a88a2]">TELEGRAM_API_ID</span> <span className="text-[#d0dfeb]">→ server environment</span></div><div><span className="text-[#6a88a2]">TELEGRAM_API_HASH</span> <span className="text-[#d0dfeb]">→ server environment</span></div></div><p className="text-[12px] leading-5 text-[#8299ae]">Ask your administrator to add both values, then refresh the integration status. No credentials, session strings, passwords, or verification codes are shown here.</p><div className="flex justify-end gap-2"><QuietButton onClick={() => setIntegration(false)}>Close</QuietButton><PrimaryButton onClick={() => { setIntegration(false); setToast("Integration status refresh requested"); }}>Refresh status</PrimaryButton></div></div></Modal>}
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}
  </AppLayout>;
}