// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/telecampaign/Accounts.tsx": () => import("../components/mockups/telecampaign/Accounts.tsx"),
  "./components/mockups/telecampaign/Calendar.tsx": () => import("../components/mockups/telecampaign/Calendar.tsx"),
  "./components/mockups/telecampaign/Campaigns.tsx": () => import("../components/mockups/telecampaign/Campaigns.tsx"),
  "./components/mockups/telecampaign/Dashboard.tsx": () => import("../components/mockups/telecampaign/Dashboard.tsx"),
  "./components/mockups/telecampaign/Groups.tsx": () => import("../components/mockups/telecampaign/Groups.tsx"),
  "./components/mockups/telecampaign/Logs.tsx": () => import("../components/mockups/telecampaign/Logs.tsx"),
  "./components/mockups/telecampaign/Settings.tsx": () => import("../components/mockups/telecampaign/Settings.tsx")
};
